version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - curl -O https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - chmod +x terraform         
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform --version
      - terraform init
  build:
    commands:
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan
