version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - git clone https://github.com/tfutils/tfenv.git ~/.tfenv
      - echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> ~/.bashrc
      - export PATH="$HOME/.tfenv/bin:$PATH"
      - tfenv install 1.6.6
      - tfenv use 1.6.6

  pre_build:
    commands:
      - /usr/bin/terraform --version     
      - /usr/bin/terraform init
  build:
    commands:
      - /usr/bin/terraform plan -out=tfplan
      - /usr/bin/terraform apply -auto-approve tfplan
